# Generated by Django 4.2.5 on 2023-09-27 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col1', models.CharField(blank=True, max_length=255)),
                ('col2', models.CharField(blank=True, max_length=255)),
                ('col3', models.CharField(blank=True, max_length=255)),
                ('col4', models.CharField(blank=True, max_length=255)),
                ('col5', models.CharField(blank=True, max_length=255)),
                ('col6', models.CharField(blank=True, max_length=255)),
                ('col7', models.CharField(blank=True, max_length=255)),
                ('col8', models.CharField(blank=True, max_length=255)),
                ('col9', models.CharField(blank=True, max_length=255)),
                ('col10', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TableCell',
        ),
        migrations.AddField(
            model_name='mytable',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.department'),
        ),
        migrations.AddField(
            model_name='mytable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
