# Generated by Django 4.2.5 on 2023-09-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_mytable_alter_department_name_delete_tablecell_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytable',
            name='user',
        ),
    ]
